### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by IsmailM** [SBCS-Bioinformatics/GEODiver#11]

**Comment by Nazrath10R** [comment]
![12714322_10208870022458510_190953899_n](https://cloud.githubusercontent.com/assets/8961165/13048294/e0e0a268-d3dc-11e5-80c4-e543c2a8d2d8.jpg)

**Comment by Nazrath10R** [comment]
@MPriebe

**Comment by IsmailM** [comment]
@MPriebe Can you send me the latest logo?

I would like to update the website with out latest logo

Thanks

**Comment by IsmailM** [comment]
@MPriebe, can you email be the source files for the latest logo.

Thanks...

**Comment by IsmailM** [comment]
Done.
