### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by IsmailM** [SBCS-Bioinformatics/GEODiver#12]

**Comment by Nazrath10R** [comment]
[FAQ.docx](https://github.com/SBCS-Bioinformatics/GEODiver/files/130655/FAQ.docx)

**Comment by Nazrath10R** [comment]
@Anisatu @MPriebe anything you want to add on?

**Comment by Anisatu** [comment]
What about something like this:

What is a Gene Set Analysis?    (or whatever we've called it in the web app)

Gene set analysis uses the difference in gene expression levels shown in a dataset, to identify significantly dysregulated gene sets (a group of genes that are involved biological function). GeoDiver allows you to carry out this analysis with a dataset that contains an experimental and control group, or using a dataset that only consists of experimental groups.

**Comment by Nazrath10R** [comment]
[FAQ.docx](https://github.com/SBCS-Bioinformatics/GEODiver/files/131652/FAQ.docx)

updated

**Comment by IsmailM** [comment]
@Nazrath10R, Firstly can you `Copy & Paste`&trade; the FAQs from the word document to the Github Repo [Wiki Page](https://github.com/SBCS-Bioinformatics/GEODiver/wiki). Would be nice to have a link on the readme... 

Secondly, how should we present this on the website?

- A totally separate page
- A Modal (like when pressing Modal Bottom Style Sheet on [Materialize](http://materializecss.com/modals.html#modal3) )
     - That way a user can access the FAQs within the app by clicking on the FAQ button (within the dropdown under user profile)
- Any other Idea?

**Comment by Nazrath10R** [comment]
Done. 

I was thinking about a separate page if it is feasible to do so and also since there is an "FAQ" button on the user profile dropdown

**Comment by IsmailM** [comment]
Done

Will be available at [www.geodiver.co.uk/faq](www.geodiver.co.uk/faq) shortly
