### ISSUE TITLE
PCA download button sometimes not working

### ISSUE THREAD

**Issue by IsmailM** [SBCS-Bioinformatics/GEODiver#20]
download button within plotly

**Comment by Nazrath10R** [comment]
Tend to get this error alot - e.g: GDS5040

Taking snapshot - this may take a few seconds
×
Sorry there was a problem downloading your png

**Comment by IsmailM** [comment]
More details please - which plot?

**Comment by Nazrath10R** [comment]
PCA plot (cumulative and explained variance plot)

no console errors

straight away after clicking the plotly download button

**Comment by IsmailM** [comment]
This is Safari specific - this should work in other browsers…

This is a bug in Plotly - See http://community.plot.ly/t/plotly-js-export-not-working/180

We will patiently wait until the plotly community fixes this - patience is a virtue :v:

**Comment by IsmailM** [comment]
https://github.com/plotly/plotly.js/issues/250

**Comment by Nazrath10R** [comment]
Tested on chrome and works. Thank you!

**Comment by IsmailM** [comment]
I'm closing this for now, since this needs to be fixed upstream from us...
