### ISSUE TITLE
Home page fonts

### ISSUE THREAD

**Issue by Nazrath10R** [SBCS-Bioinformatics/GEODiver#26]

**Comment by Nazrath10R** [comment]
<h1 class="header center teal-text text-lighten-2" style="font-weight: 500;
	color: rgba(254, 254, 254, 0.93);
	&nbsp;text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">GeoDiver</h1>

	<h5 class="header col s12 light" style="font-weight: 500;
	color: #fff;
	text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">  An easy to use web tool for analysing GEO datasets.</h5>

**Comment by IsmailM** [comment]
Done
