### ISSUE TITLE
Toptable paging CSS issue

### ISSUE THREAD

**Issue by sureshhewabi** [SBCS-Bioinformatics/GEODiver#30]
<img width="799" alt="screen shot 2016-02-15 at 4 09 41 pm" src="https://cloud.githubusercontent.com/assets/5387193/13054284/effcd9be-d400-11e5-8d54-d6291840ac9b.png">

**Comment by IsmailM** [comment]
Do you still see this?

**Comment by IsmailM** [comment]
Can we close this?

**Comment by IsmailM** [comment]
No Respone….

Closing for now.
