### ISSUE TITLE
Bar show after selection of GSEA

### ISSUE THREAD

**Issue by sureshhewabi** [SBCS-Bioinformatics/GEODiver#38]
<img width="776" alt="screen shot 2016-02-16 at 12 43 55 am" src="https://cloud.githubusercontent.com/assets/5387193/13064983/9d6c2e12-d44f-11e5-97a6-f82fc873ad43.png">

**Comment by IsmailM** [comment]
Can you show me this?

**Comment by sureshhewabi** [comment]
it is not there now. You can close it :D
