### ISSUE TITLE
CSS issue - PC2 label appearance - GSD5093

### ISSUE THREAD

**Issue by sureshhewabi** [SBCS-Bioinformatics/GEODiver#39]
<img width="589" alt="screen shot 2016-02-16 at 12 38 34 am" src="https://cloud.githubusercontent.com/assets/5387193/13064991/b6c4b604-d44f-11e5-95fd-0cb63536dde6.png">

**Comment by sureshhewabi** [comment]
There is a spelling mistake too. "Ananlyse"

**Comment by IsmailM** [comment]
Done
