### ISSUE TITLE
GAGE results not appearing 

### ISSUE THREAD

**Issue by Anisatu** [SBCS-Bioinformatics/GEODiver#43]
![gage results](https://cloud.githubusercontent.com/assets/16674855/13126129/407186b2-d5c1-11e5-8c9b-c801f8cbf57f.PNG)

When GAGE is attempted on GDS5040 and GDS5075, GAGE results do not appear (DGEA results are fine). This issue happens regardless of the GAGE analysis type or gene set used. They are not from the same organism (human and mouse, respectively).

**Comment by sureshhewabi** [comment]
Hi Anisa, I could not replicate this issue for GDS5040. I got heatmapt, top tables, interact networks for GDS 5040.

<img width="778" alt="screen shot 2016-02-17 at 11 57 38 pm" src="https://cloud.githubusercontent.com/assets/5387193/13129114/9d6ab09e-d5d2-11e5-9609-ae3ec08bd7b6.png">
<img width="778" alt="screen shot 2016-02-17 at 11 58 08 pm" src="https://cloud.githubusercontent.com/assets/5387193/13129117/a382d0c4-d5d2-11e5-841b-eb7967db11a6.png">
<img width="799" alt="screen shot 2016-02-17 at 11 58 27 pm" src="https://cloud.githubusercontent.com/assets/5387193/13129121/a7a077d8-d5d2-11e5-996b-92082306edff.png">

Regarding GDS5075, according to my understanding, there are no real pathway results for this, because it has few samples and few matching entrez IDs. May be dataset issue, again I could not replicate the issue

**Comment by sureshhewabi** [comment]
For some reason GDS5075 does not give any results: 
   [1] "Note: 5702 of 26767 unique input IDs unmapped."
   [1] "No heatmap produced for two-way perturbed gene sets, only 1 or none signficant."
   [1] "there are 0 signficantly two-direction perturbed gene sets"

**Comment by sureshhewabi** [comment]
I tried with your original script and it gave me 56 results. if time permits I will look into that.

**Comment by Anisatu** [comment]
Yeah, I still get the error for GDS5040 (it could be something specific to my computer/account). I think we'll get away with not figuring out how to fix the GDS5075 one if we don't finish have enough time.

**Comment by IsmailM** [comment]
GDS5040 works for me as well on GeoDiver - I simply had to wait 10 seconds for the results to appear (that’s a bug in itself).

It is possible that it is something specific to your computer, delete your browser history. 

If that doesn’t work, try using chrome and then right clicking after the results appear (or rather don’t appear) and click on ‘inspect’ and then see if you see any errors in the [browser console](https://developer.chrome.com/devtools/docs/console). If you see anything, please report here. 

Please do the above for any bugs seen.

Thanks.

**Comment by Anisatu** [comment]
So tried it again, and it didn't work. When I checked browser console, I saw the following message: "http://geodiver.co.uk/analyse Failed to load resource: the server responded with a status of 504 (Gateway Time-out)"

Each time I've tried to analyse the dataset, it seems to be loading for a while (about a minute or two), before presenting the "There seems to be an unidentified Error." message.

**Comment by IsmailM** [comment]
Thanks,

This needs to be fixed by updating the nginx config….

Default is 60 seconds, maybe update to a few minutes?

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout

```
location / {
     proxy_read_timeout 240s;
}
 ```

**Comment by Nazrath10R** [comment]
Worked fine for me. I saw the same result as in Suresh's screenshot

**Comment by IsmailM** [comment]
This could potentially be slightly affected by internet speed… 

GeoDiver should work for all devices and users - most research institutions globally have really rubbish internet. 

we should really test our website, at all internet speeds… (if someone wants to quickly test the effect of network speed on our website by emulating different network speed by throttling in [chrome web tools](https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/network-conditions?hl=en) and potentially put this in the write up )

**Comment by Nazrath10R** [comment]
Emulated network conditions of 50 kb/s, 250 kb/s, 450 kb/s, 750 kb/s, 1Mb/s, 4 Mb/s, 2Mb/s and 30 Mb/s
for GDS5040.

geodiver.co.uk worked for all of them, with only the two ggplots (Boxplot and Volcano) taking some time to load (~20-30 seconds) for the lowest two speeds. I am happy to test it at any custom throttles if suggested. I shall also include this in the non-functional requirement testing in the write up.

**Comment by IsmailM** [comment]
Have applied the proxy_timeout fix…

Both GDS5040 and GDS5075 are now working.

Reopen this issue, if you still have issues running Gage on the these two datasets.
