### ISSUE TITLE
Visualisation only appearing in 'My Results'

### ISSUE THREAD

**Issue by Anisatu** [SBCS-Bioinformatics/GEODiver#44]
![image](https://cloud.githubusercontent.com/assets/16674855/13126518/a3fb0734-d5c2-11e5-90d1-4eeac7837ec3.png)

When analysis is carried out on GDS5089, the following error occurs. However, if the same analysis is accessed through 'My Results', all of the results and visualisation appear as normal.

**Comment by IsmailM** [comment]
Fixed
