### ISSUE TITLE
Group name consistency

### ISSUE THREAD

**Issue by Nazrath10R** [SBCS-Bioinformatics/GEODiver#56]
When selecting the factors, it says Group A and B and in the Results, Group 1 and 2.
I suggest we stick to 1 and 2.

Ideal solution would be to use the factor name itself after selected

**Comment by IsmailM** [comment]
Actually imo, if there are 5 factors in a group, and one in the other, the switch would look weird…

Shall we simply call it Group A and Group B, but then have a tooltip that shows all the factors in the group on hover…


What do you think?

**Comment by Anisatu** [comment]
Yeah, I definitely agree @IsmailM , there are loads of datasets where users would probably put several factors into 1 group, your suggestion is a good compromise.
