### ISSUE TITLE
plotly.py (Download plot as png) NOT WORKING

### ISSUE THREAD

**Issue by GrainsofSalt** [SBCS-Bioinformatics/GEODiver#64]
Tested in all browsers, including chrome. 

The "Download plot as png" button on the action bar is not working. 
I get the message "Taking snapshot - this may take a few seconds" directly followed by "Sorry there was a problem downloading your snapshot!"

Any ideas?

**Comment by GrainsofSalt** [comment]
Did I post this in the wrong place?

**Comment by IsmailM** [comment]
Hey @GrainsofSalt,

Are you seeing this issue within GeoDiver or within another app?

**Comment by GrainsofSalt** [comment]
Wow quick response. I am seeing an issue with Plotly.py. I think I definitely posted this in the wrong section. Not sure why I was directed here. I was just looking at a plotly post. Sorry about that.

**Comment by IsmailM** [comment]
no worries - I would suggest creating the issue at https://github.com/plotly/plotly.py

**Comment by Nazrath10R** [comment]
On my browser (Safari), when I click on it, I get redirected to a page with the static picture

**Comment by GrainsofSalt** [comment]
It might have something to do with the fact that I am generating it as a div to display within html. But I would still like the option to export the graph as a picture. I'm not sure what the issue is.
